" Generated by wallpaper script
hi Normal guibg=dcol_mode="dark" guifg=dcol_pry1="14130C"
hi Comment guifg=#a6adc8
hi CursorLine guibg=#313244
hi Visual guibg=#45475a
" Add more highlight groups as needed
